apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p8hs0pb6i-python
  janus-idp.io/tekton: p8hs0pb6i-python
  backstage.io/kubernetes-id: p8hs0pb6i-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p8hs0pb6i-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
